services:
  universal-encoder:
    build: .
    image: code418/universal-encoder:latest
    container_name: universal-encoder
    environment:
      - TARGET_DIR=/data
      - CRF=22
      - PRESET=veryfast
      - AUDIO_BITRATE=160k
      - USE_NVENC=false
      - KEEP_ORIGINAL=false
      - PRESERVE_TIMESTAMPS=true
      - DRY_RUN=false
    volumes:
      - ./data:/data
    ports:
      - "11223:11223"
    restart: unless-stopped
