name: Build & Push Docker image

on:
  push:
    branches: [ "main" ]
    tags: [ "v*", "v*.*", "v*.*.*" ]
  workflow_dispatch:

permissions:
  contents: read
  packages: write

env:
  IMAGE_NAME: universal-encoder

jobs:
  docker:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Read version
        id: version
        shell: bash
        run: |
          if [[ "${GITHUB_REF_TYPE}" == "tag" ]]; then
            v="${GITHUB_REF_NAME#v}"
          elif [[ -f VERSION ]]; then
            v="$(cat VERSION)"
          else
            v="dev-${GITHUB_SHA::7}"
          fi
          echo "version=$v" >> "$GITHUB_OUTPUT"
          echo "Version: $v"

      - name: Set image names
        id: img
        shell: bash
        run: |
          echo "dh=${{ secrets.DOCKERHUB_USERNAME }}/${{ env.IMAGE_NAME }}" >> "$GITHUB_OUTPUT"
          echo "gh=ghcr.io/${{ github.repository_owner }}/${{ env.IMAGE_NAME }}" >> "$GITHUB_OUTPUT"

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GHCR
        if: ${{ github.event_name != 'pull_request' }}
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Login to Docker Hub (if secrets provided)
        if: ${{ secrets.DOCKERHUB_USERNAME && secrets.DOCKERHUB_TOKEN }}
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Compute tags
        id: tags
        shell: bash
        env:
          VERSION: ${{ steps.version.outputs.version }}
          DH: ${{ steps.img.outputs.dh }}
          GH: ${{ steps.img.outputs.gh }}
        run: |
          TAGS="$GH:$VERSION\n$GH:sha-${GITHUB_SHA::7}\n$DH:$VERSION\n$DH:sha-${GITHUB_SHA::7}"
          if [[ "${GITHUB_REF_TYPE}" == "tag" ]] || [[ "${GITHUB_REF_NAME}" == "main" ]]; then
            TAGS="$TAGS\n$GH:latest\n$DH:latest"
          fi
          echo -e "tags<<EOF" >> "$GITHUB_OUTPUT"
          echo -e "$TAGS" >> "$GITHUB_OUTPUT"
          echo "EOF" >> "$GITHUB_OUTPUT"
          echo -e "Resolved tags:\n$TAGS"

      - name: Build & Push
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          platforms: linux/amd64,linux/arm64
          build-args: |
            VERSION=${{ steps.version.outputs.version }}
          tags: ${{ steps.tags.outputs.tags }}
          labels: |
            org.opencontainers.image.title=Universal Encoder
            org.opencontainers.image.version=${{ steps.version.outputs.version }}
            org.opencontainers.image.revision=${{ github.sha }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
